import React from 'react';
import { SEOHead } from '../components/common/SEOHead';
import { Breadcrumbs } from '../components/common/Breadcrumbs';
import { FileText, AlertTriangle } from 'lucide-react';
import { SITE_CONFIG } from '../config/site';

export const TermsOfUse: React.FC = () => {
  return (
    <>
      <SEOHead
        title="Terms of Use — StudyTools Hub"
        description="Review the Terms of Use for StudyTools Hub. Read calculation disclaimers, financial estimates notices, and health screening guidelines."
        canonicalPath="/terms"
      />

      <div className="max-w-4xl mx-auto px-4 py-8">
        <Breadcrumbs items={[{ label: 'Terms of Use' }]} />

        <div className="mb-8">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2.5 rounded-lg bg-[#2563EB] text-white">
              <FileText className="w-5 h-5" />
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold text-[#171A19] dark:text-[#EAEFEA] tracking-tight">
              Terms of Use
            </h1>
          </div>
          <p className="text-sm text-[#626966] dark:text-[#A2ABA6]">
            Last Updated: September 16, 2026
          </p>
        </div>

        <div className="bg-white dark:bg-[#181E1C] rounded-xl p-6 sm:p-10 border border-[#E5E8E5] dark:border-[#2A3430] space-y-8 text-[#171A19] dark:text-[#EAEFEA] text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing and using <strong>{SITE_CONFIG.name}</strong>, you acknowledge and agree to comply with these Terms of Use. If you do not agree with any part of these terms, please refrain from using the tools and website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">
              2. Informational & Educational Purposes Only
            </h2>
            <p>
              All online calculators, converters, grade converters, and tools provided on {SITE_CONFIG.name} are designed for general educational, academic, and informational purposes. While we strive to maintain absolute precision in math algorithms, users are responsible for double-checking critical calculations prior to official academic transcript submissions, exam registrations, or financial decisions.
            </p>
          </section>

          <section className="p-4 rounded-lg bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800 text-amber-900 dark:text-amber-200">
            <h3 className="font-bold text-base flex items-center gap-2 mb-2">
              <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" />
              Financial & Health Disclaimers
            </h3>
            <ul className="list-disc list-inside space-y-2 text-xs sm:text-sm">
              <li>
                <strong>Financial EMI & Profit Calculators:</strong> All monthly installment (EMI), total interest, and profit margin outputs are mathematical estimates. They do not constitute binding financial, banking, tax, or loan quotes.
              </li>
              <li>
                <strong>Health & BMI Calculator:</strong> Body Mass Index (BMI) outputs provide general population screening categories. They do NOT constitute medical diagnosis, advice, or treatment recommendations. Always consult a qualified medical professional for health evaluations.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">
              3. Institutional Variation (CGPA / GPA)
            </h2>
            <p>
              Academic boards and universities establish independent grading handbooks and CGPA-to-percentage conversion factors (e.g., 9.5 vs 10.0 multiplier). {SITE_CONFIG.name} provides configurable multipliers for flexibility, but users must verify their specific institution's official policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">
              4. Limitation of Liability
            </h2>
            <p>
              {SITE_CONFIG.name} and its creators shall not be held liable for any indirect, incidental, or consequential damages resulting from errors, omissions, or reliance upon any calculation result generated by the website.
            </p>
          </section>
        </div>
      </div>
    </>
  );
};
