import { CalculatorInfo } from '../types';

export const CALCULATORS: CalculatorInfo[] = [
  {
    id: 'percentage',
    name: 'Percentage Calculator',
    slug: 'percentage-calculator',
    description: 'Calculate marks percentage, fraction conversion, and score ratios instantly.',
    category: 'Student',
    iconName: 'Percent',
    route: '/calculators/percentage-calculator',
    isPopular: true,
  },
  {
    id: 'cgpa',
    name: 'CGPA Calculator',
    slug: 'cgpa-calculator',
    description: 'Convert CGPA to percentage with customizable university grading scale multipliers.',
    category: 'Student',
    iconName: 'GraduationCap',
    route: '/calculators/cgpa-calculator',
    isPopular: true,
  },
  {
    id: 'attendance',
    name: 'Attendance Calculator',
    slug: 'attendance-calculator',
    description: 'Find current attendance %, classes you can safely skip, or classes needed to hit your target.',
    category: 'Student',
    iconName: 'CalendarCheck',
    route: '/calculators/attendance-calculator',
    isPopular: true,
  },
  {
    id: 'gpa',
    name: 'GPA Calculator',
    slug: 'gpa-calculator',
    description: 'Calculate semester or cumulative weighted Grade Point Average (GPA) across subjects.',
    category: 'Student',
    iconName: 'Award',
    route: '/calculators/gpa-calculator',
    isPopular: true,
  },
  {
    id: 'age',
    name: 'Age Calculator',
    slug: 'age-calculator',
    description: 'Calculate exact age in years, months, days, total days, and next birthday countdown.',
    category: 'Everyday',
    iconName: 'Clock',
    route: '/calculators/age-calculator',
    isPopular: true,
  },
  {
    id: 'emi',
    name: 'EMI Calculator',
    slug: 'emi-calculator',
    description: 'Calculate monthly loan EMI, total interest payable, and total loan cost breakdown.',
    category: 'Finance',
    iconName: 'Calculator',
    route: '/calculators/emi-calculator',
    isPopular: true,
  },
  {
    id: 'discount',
    name: 'Discount Calculator',
    slug: 'discount-calculator',
    description: 'Determine exact savings and final price after applying sale discount percentages.',
    category: 'Finance',
    iconName: 'Tag',
    route: '/calculators/discount-calculator',
  },
  {
    id: 'bmi',
    name: 'BMI Calculator',
    slug: 'bmi-calculator',
    description: 'Calculate Body Mass Index (BMI) and view health category classification ranges.',
    category: 'Health',
    iconName: 'Activity',
    route: '/calculators/bmi-calculator',
    isPopular: true,
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    slug: 'unit-converter',
    description: 'Convert length, weight, temperature, and time between metric and imperial units.',
    category: 'Math',
    iconName: 'ArrowLeftRight',
    route: '/calculators/unit-converter',
    isPopular: true,
  },
  {
    id: 'profit-loss',
    name: 'Profit & Loss Calculator',
    slug: 'profit-loss-calculator',
    description: 'Calculate profit or loss amounts and margin percentages from cost and selling prices.',
    category: 'Finance',
    iconName: 'TrendingUp',
    route: '/calculators/profit-loss-calculator',
  },
];
